language: go

env:
    - GO111MODULE=on

go:
    - 1.16

os:
    - linux
    - osx
    - windows

install:
    - go get -t -v ./...
    - go install ./cmd/modd

script:
    - go test -v -race ./...

notifications:
    email:
        - aldo@corte.si
